# Generated by Django 3.2.6 on 2021-10-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='condition',
            field=models.TextField(default='Условие', max_length=512),
        ),
    ]
