# Generated by Django 3.2.6 on 2021-11-06 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='task',
            name='condition',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='task',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.collection'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
